<?php

namespace App\Models\Collections;

use App\Collections\ProductCollection;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    //Gán collection mới cho model Post
    public function newCollection(array $models = [])
    {
        return new ProductCollection($models); // TODO: Change the autogenerated stub
    }
}
